project:
  type: website

website:
  title: "Oldham Lab"
  navbar:
    right:
      - people.qmd
      - papers.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true



