project:
  type: website

website:
  title: "Oldham Lab"
  navbar:
    right:
      - people.qmd
      - papers.qmd
      - contact.qmd
  google-analytics: "G-KZ6PJ54VTV"
  cookie-consent: true
  twitter-card: 
    creator: "@wm_oldham"

format:
  html:
    theme: 
    - cosmo
    - custom.scss
    css: styles.css
    toc: true
    link-external-newwindow: true



